// Mocks generated by Mockito 5.4.6 from annotations
// in ahoy_flutter/test/ahoy_flutter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:ahoy_flutter/src/models/configuration.dart' as _i2;
import 'package:ahoy_flutter/src/network/ahoy_http_client.dart' as _i4;
import 'package:ahoy_flutter/src/network/request_interceptor.dart' as _i5;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConfiguration_0 extends _i1.SmartFake implements _i2.Configuration {
  _FakeConfiguration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AhoyHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAhoyHttpClient extends _i1.Mock implements _i4.AhoyHttpClient {
  MockAhoyHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Configuration get configuration => (super.noSuchMethod(
        Invocation.getter(#configuration),
        returnValue: _FakeConfiguration_0(
          this,
          Invocation.getter(#configuration),
        ),
      ) as _i2.Configuration);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  List<_i5.RequestInterceptor> get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: <_i5.RequestInterceptor>[],
      ) as List<_i5.RequestInterceptor>);

  @override
  _i6.Future<_i3.Response> post({
    required String? path,
    String? body,
    Map<String, String>? additionalHeaders,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [],
          {
            #path: path,
            #body: body,
            #additionalHeaders: additionalHeaders,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [],
            {
              #path: path,
              #body: body,
              #additionalHeaders: additionalHeaders,
              #queryParameters: queryParameters,
            },
          ),
        )),
      ) as _i6.Future<_i3.Response>);
}
